export class InvoiceList{
    invoicelistId:number
    rent:number
    rentTax:number
    rentTotal:number
    rentUsagePeriod:string
    brokerageFee:number
    brokerageFeeTax:number
    brokerageFeeTotal:number
    brokerageFeeUsagePeriod:string
    serviceFee:number
    serviceFeeTax:number
    serviceFeeTotal:number
    serviceFeeUsagePeriod:string
    parkingFee:number
    parkingFeeTax:number
    parkingFeeTotal:number
    parkingStartDate:string
    parkingEndDate:string
    bicycleParkingFee:number
    bicycleParkingFeeTax:number
    bicycleParkingFeeTotal:number
    bicycleParkingStartDate:string
    bicycleParkingEndDate:string
    keymoney:number
    keymoneyTax:number
    keymoneyTotal:number
    keymoneyStartDate:string
    keymoneyEndDate:string
    shikikin:number
    shikikinTax:number
    shikikinTotal:number
    shikikinStartDate:string
    shikikinEndDate:string
    deposit:number
    depositTax:number
    depositTotal:number
    depositStartDate:string
    depositEndDate:string
    renewalFee:number
    renewalFeeTax:number
    renewalFeeTotal:number
    renewalFeeStartDate:string
    renewalFeeEndDate:string
    repairCost:number
    repairCostTax:number
    repairCostTotal:number
    repairCostStartDate:string
    repairCostEndDate:string
    penaltyFee:number
    penaltyFeeTax:number
    penaltyFeeTotal:number
    penaltyFeeStartDate:string
    penaltyFeeEndDate:string
    signboard:number
    signboardTax:number
    signboardTotal:number
    signboardStartDate:string
    signboardEndDate:string
    electricBill:number
    electricBillTax:number
    electricUsageAmount:number
    electricBillUsageFee:number
    electricBillTotal:number
    electricBillStartDate:string
    electricBillEndDate:string
    waterBill:number
    waterBillTax:number
    waterUsageAmount:number
    waterBillUsageFee:number
    waterBillTotal:number
    waterBillStartDate:string
    waterBillEndDate:string
    gasBill:number
    gasBillTax:number
    gasUsageAmount:number
    gasBillUsageFee:number
    gasBillTotal:number
    gasBillStartDate:string
    gasBillEndDate:string
    constructionBill:number
    constructionBillTax:number
    constructionBillTotal:number
    constructionBillUsagePeriod:string
    workNameFirst:String
    workAmountFirst:number
    workTaxFirst:number
    workAmountTotalFirst:number
    workUsagePeriodFirst:string
    workNameSecond:string
    workAmountSecond:number
    workTaxsecond:number
    workTotalSecond:number
    workUsagePeriodSecond:string
    total:number
    }